env:
  group: gtc-rg-www-dev
  template: common.yml
  rgEnvironment: Development
  rgName: rg-www-dev-001
  locationName: West US 2
  appInsightsName: appi-www-dev-001
  kvName: kv-www-dev-001
  storageName: stwwwdev001
  workspaceName: work-www-dev-001
                    