on:
  push:
    branches:
    - '*'
    paths:
    - .azure/*
    - .github/workflows/*

env:
  subscriptionId: ${{ secret.SUBSCRIPTION_ID }}
  companyInfix: 'gtc'
  coutnerInfix: '001'
  productInfix: 'www'
  rgLocation: 'westus2'
  subscriptionService: AZURE_SERVICE_CONNECTION
  infrastructurePath: ${{ github.workspace }}/.azure

jobs:  
  development_landing_zone:
    if: (github.ref != 'refs/heads/main')
    runs-on: ubuntu-latest
    environment: development
    env:
      environmentInfix: 'dev'
    uses: goodtocode/goodtocode.github.io/.github/workflows/reusable-workflows/landingzone-infrastructure-steps.yml@3-create-devops-and-azure-static-infrastructure
    with:
      armPath: ${{ env.infrastructurePath }}
      subscriptionId: ${{ env.subscriptionId }}
      subscriptionService: ${{ env.subscriptionService }}
      rgName: '${{ env.companyInfix }}-rg-${{ env.productInfix }}-${{ env.environmentInfix }}-${{ env.coutnerInfix }}'
      rgLocation: ${{ env.rgLocation }}
      appiName: 'appi-${{ env.productInfix }}-${{ env.environmentInfix }}-${{ env.coutnerInfix }}'
      kvName: 'kv-${{ env.productInfix }}-${{ env.environmentInfix }}-${{ env.coutnerInfix }}'
      stName: 'st-${{ env.productInfix }}-${{ env.environmentInfix }}-${{ env.coutnerInfix }}'
      workName: 'work-${{ env.productInfix }}-${{ env.environmentInfix }}-${{ env.coutnerInfix }}'
  