on:
  push:
    branches:
    - '*'
    paths:
    - .azure/*
    - .github/workflows/*

env:  
  companyInfix: 'gtc'
  coutnerInfix: '001'
  productInfix: 'www'
  rgLocation: 'westus2'
  subscriptionService: AZURE_SERVICE_CONNECTION
  infrastructurePath: ${{ github.workspace }}/.azure

jobs:
  development_landing_zone:
    if: (github.ref != 'refs/heads/main')
    runs-on: ubuntu-latest
    environment: development
    env:
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
      environmentInfix: 'dev'
    uses: goodtocode/goodtocode.github.io/.github/workflows/test.yml@3-create-devops-and-azure-static-infrastructure
