on:
  push:
    branches:
    - '*'
    paths:
    - .azure/*
    - .github/workflows/*

env:
  subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
  environmentInfix: 'dev'

jobs:
  development_landing_zone:
    uses: ./.github/workflows/test.yml
