on:
  push:
    branches:
    - '*'
    paths:
    - .azure/*
    - .github/workflows/*
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: development
        type: environment
      environmentInflix:
        description: 'environment (short name) for resources'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod
      companyInflix:
        description: 'Company abbreviation'
        required: true 
        type: string
        default: 'gtc'
      counterInflix:
        description: 'Counter for resources'
        required: true 
        type: string
        default: '001'
      productInflix:
        description: 'Product abbreviation'
        required: true 
        type: string
        default: 'www'
      rgLocation:
        description: 'Location for resources'
        required: true 
        type: string
        default: 'westus2'

jobs:
  deploy_landing_zone:
    uses: ./.github/workflows/landingzone-infrastructure-steps.yml
    with:
      armPath: '${{ github.workspace }}/.azure'
      armSuffix: 'bicep'
      rgName: '${{ inputs.companyInflix }}-rg-${{ inputs.productInflix }}-${{ inputs.environmentInflix }}-${{ inputs.coutnerInflix }}'
      rgLocation: ${{ inputs.rgLocation }}
      appiName: 'appi-${{ inputs.productInflix }}-${{ inputs.environmentInflix }}-${{ inputs.coutnerInflix }}'
      kvName: 'kv-${{ inputs.productInflix }}-${{ inputs.environmentInflix }}-${{ inputs.coutnerInflix }}'
      stName: 'st-${{ inputs.productInflix }}-${{ inputs.environmentInflix }}-${{ inputs.coutnerInflix }}'
      workName: 'work-${{ inputs.productInflix }}-${{ inputs.environmentInflix }}-${{ inputs.coutnerInflix }}'
    secrets: inherit
