on:
  push:
    branches:
    - '*'
    paths:
    - .azure/*
    - .github/workflows/*

jobs:
  development_landing_zone:
    if: (github.ref != 'refs/heads/main')
    runs-on: ubuntu-latest
    environment: development
    env:
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
      environmentInfix: 'dev'
    uses: ./.github/workflows/test.yml
