on:
  push:
    branches:
    - '*'
    paths:
    - .azure/*
    - .github/workflows/*

env:
  template: ./.github/variables/common.yml
  subscriptionId: $subscriptionId
  subscriptionService: AZURE_SERVICE_CONNECTION

jobs:  
  development_Stage_deploy_landing_zone:
    if: (github.ref != 'refs/heads/main')
    runs-on: ubuntu-latest    
    env:
      template: ./.github/variables/development.yml    
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/reusable-workflows/landingzone-infrastructure-steps.yml
      with:
        armPath: $infrastructurePath
        subscriptionId: $subscriptionId 
        subscriptionService: $subscriptionService 
        rgName: $rgName
        rgLocation: $rgLocation
        appiName: $appiName
        kvName: $kvName
        stName: $stName
        workName: $workName
  
  production_Stage_deploy_landing_zone:
    if: (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest    
    env:
      template: ./.github/variables/production.yml
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/reusable-workflows/landingzone-infrastructure-steps.yml 
      with:
        armPath: $infrastructurePath
        subscriptionId: $subscriptionId 
        subscriptionService: $subscriptionService 
        rgName: $rgName
        rgLocation: $rgLocation
        appiName: $appiName
        kvName: $kvName
        stName: $stName
        workName: $workName
                    