on:
  push:
    branches:
    - '*'
    paths:
    - .azure/*
    - .github/workflows/*
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: development
        type: environment
      environmentInflix:
        description: 'environment (short name) for resources'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod
      companyInflix:
        description: 'Company abbreviation'
        required: true 
        type: string
        default: 'gtc'
      counterInflix:
        description: 'Counter for resources'
        required: true 
        type: string
        default: '001'
      productInflix:
        description: 'Product abbreviation'
        required: true 
        type: string
        default: 'www'
      rgLocation:
        description: 'Location for resources'
        required: true 
        type: string
        default: 'westus2'

env:
  azcredentials: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  az_login:
    runs-on: ubuntu-latest
    environment: development
    env:
      client_id: ${{ secrets.CLIENT_ID }}
      tenant_id: ${{ secrets.TENANT_ID }}
      subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      client_secret: ${{ secrets.CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - if: ${{ env.client_id == '85c6a127-ff79-4c86-9522-67262bc82b02' }}
        run: echo 'C MATCH!'
      - if: ${{ env.client_id != '85c6a127-ff79-4c86-9522-67262bc82b02' }}
        run: echo 'C DOES NOT match!'
      - if: ${{ env.tenant_id == 'ad6529dd-8db1-4015-a53d-6ae395fc7e39' }}
        run: echo 'T MATCH!'
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ env.client_id }}","clientSecret":"${{ env.client_secret }}","subscriptionId":"${{ env.subscription_id }}","tenantId":"${{ env.tenant_id }}"}'

  deploy_landing_zone:
    needs: [az_login]
    uses: ./.github/workflows/landingzone-infrastructure-steps.yml
    with:
      armPath: '${{ github.workspace }}/.azure'
      armSuffix: 'bicep'
      rgName: '${{ inputs.companyInflix }}-rg-${{ inputs.productInflix }}-${{ inputs.environmentInflix }}-${{ inputs.coutnerInflix }}'
      rgLocation: ${{ inputs.rgLocation }}
      appiName: 'appi-${{ inputs.productInflix }}-${{ inputs.environmentInflix }}-${{ inputs.coutnerInflix }}'
      kvName: 'kv-${{ inputs.productInflix }}-${{ inputs.environmentInflix }}-${{ inputs.coutnerInflix }}'
      stName: 'st-${{ inputs.productInflix }}-${{ inputs.environmentInflix }}-${{ inputs.coutnerInflix }}'
      workName: 'work-${{ inputs.productInflix }}-${{ inputs.environmentInflix }}-${{ inputs.coutnerInflix }}'
    secrets:
      azureCredentials: $azcredentials
