name: landingzone-infrastructure-steps.yml

on:
  workflow_call:
    inputs:
      appiName:
        description: 'Name of the appi- resource to deploy - Example: appi-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string
      armPath:
        description: 'Path to ARM files - Example: ./.azure'
        required: true
        type: string
      armSuffix:
        description: 'ARM file suffix. json or bicep'
        required: false
        type: string
        default: 'json'
      azureCredentials:
        description: 'Azure AD Service Principle (App Registration) to use for deployment - Default: secrets.AZURE_CREDENTIALS'
        required: false
        type: string
        default: ${{ github.event.secrets.AZURE_CREDENTIALS }}
      kvName:
        description: 'Name of the kv- resource to deploy - Example: kv-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string
      rgLocation:
        description: 'Azure Region of the resource group - Example: westus2'
        required: true
        type: string
      rgName:
        description: 'Name of Azure Resource Group - Example: COMPANY-rg-PRODUCT-001'
        required: true
        type: string
      stName:
        description: 'Name of the st- resource to deploy - Example: stPRODUCTENVIRONMENT001'
        required: true
        type: string
      workName:
        description: 'Name of the work- resource to deploy - Example: work-PRODUCT-ENVIRONMENT-001'
        required: true
        type: string

jobs:
  check-secret:
      runs-on: ubuntu-latest
      environment: development
      outputs:
        secret-exists: ${{ steps.secret-exists.outputs.defined }}
      steps:
          - id: secret-exists
            if: ${{ github.event.inputs.azureCredentials != '' }}
            run: echo "azureCredentials exists"
            env:
                otherEnv: ${{ github.event.secrets.AZURE_CREDENTIALS }}

  error-secret:
      runs-on: ubuntu-latest
      environment: development
      needs: [check-secret]
      if: "${{ (needs.check-secret.outputs.secret-exists == 'true') && contains(github.event.inputs.azureCredentials, 'clientId') && contains(github.event.inputs.azureCredentials, 'clientSecret') && contains(github.event.inputs.azureCredentials, 'subscriptionId') && contains(github.event.inputs.azureCredentials, 'tenantId') }}"
      steps:
        - run: echo "azureCredentials has properties"

  deploy_landingzone_step:
    runs-on: ubuntu-latest
    environment: development
    needs: [check-secret]
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ github.event.inputs.azureCredentials }}
    - name: Deploy ${{ github.event.inputs.stName }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName }} --template-file ${{ github.event.inputs.armPath }}/st-storageaccount${{ github.event.inputs.armSuffix }} --parameters  ${{ github.event.inputs.armPath }}/st-storageaccount.parameters${{ github.event.inputs.armSuffix }} -name "${{ github.event.inputs.stName }}"
    - name: Deploy ${{ github.event.inputs.workName }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName }} --template-file ${{ github.event.inputs.armPath }}/work-loganalyticsworkspace${{ github.event.inputs.armSuffix }} --parameters  ${{ github.event.inputs.armPath }}/work-loganalyticsworkspace.parameters${{ github.event.inputs.armSuffix }} -name "${{ github.event.inputs.workName }}"
    - name: Deploy ${{ github.event.inputs.appiName }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName }} --template-file ${{ github.event.inputs.armPath }}/appi-applicationinsights${{ github.event.inputs.armSuffix }} --parameters  ${{ github.event.inputs.armPath }}/appi-applicationinsights.parameters${{ github.event.inputs.armSuffix }} -name "${{ github.event.inputs.appiName }}" -workName "${{ github.event.inputs.workName }}"
    - name: Deploy ${{ github.event.inputs.kvName }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ github.event.inputs.rgName }} --template-file ${{ github.event.inputs.armPath }}/kv-keyvault${{ github.event.inputs.armSuffix }} --parameters  ${{ github.event.inputs.armPath }}/kv-keyvault.parameters${{ github.event.inputs.armSuffix }} -name "${{ github.event.inputs.kvName }}"
                    